### ISSUE TITLE
Christine Movius D&Dr

### ISSUE THREAD

**Issue by christine-sm** [ga-dc/wdi8-project2-gallery#1]
Linking this now in case I forget over the weekend: https://github.com/cmmovius/dndr

For this project, I am creating a Dungeons and Dragons app (D&Dr) where users can CRUD a campaign, characters, a dungeon master (DM), and adventure chapters.

**Comment by beckybeauchamp1** [comment]
Hi Christine,

Great job on all of your wireframes, ERD, and user stories! Everything looks good, just continue to focus on implementing your MVP first then try to tackle your Silver and Bronze. Please let me know if you have any further questions :+1:
