### ISSUE TITLE
Bipin's project cheerup

### ISSUE THREAD

**Issue by ghost** [ga-dc/wdi8-project2-gallery#10]
https://github.com/Bneupane/cheerup

**Comment by amaseda** [comment]
### Re: Planning

:+1: Looks good. A couple notes.

#### User Stories

Encourage you to create user stories that outline specific functionality in your application (e.g., "When the user clicks this button, ____ happens").

#### Wireframe

I would start out by creating individual views that map to RESTful actions (i.e., index, show, new, edit). From there, you can work on combining them (e.g., putting a new form on the index page) as you indicated you wanted to do during our brief meeting on Friday.
