### ISSUE TITLE
Ryans Factorio Map Share

### ISSUE THREAD

**Issue by rkrolick** [ga-dc/wdi8-project2-gallery#12]
I plan to make a site where users can post and share maps for the game Factorio

ERD and Wireframe can be found in the planning folder here: [https://github.com/rkrolick/wdi_project2](https://github.com/rkrolick/wdi_project2)

**Comment by nolds9** [comment]
:+1:  Planning docs look great Ryan. Looks like you're gonna need a `has many through` relationship between `users` and `comments`
