### ISSUE TITLE
Matt's NBA Stats

### ISSUE THREAD

**Issue by MattLeeStevens** [ga-dc/wdi8-project2-gallery#13]
https://github.com/MattLeeStevens/nbaStats

**Comment by mattscilipoti** [comment]
:+1: Looks good.

You may want to add a few silver/gold User Stories.  I expect you will complete these stories before Wednesday.

**Comment by mattscilipoti** [comment]
None of these stories talk about dynamically showing graphs on the index page.  I recommend you add that as Silver, commit your changes in a branch, then get these to work.  :)
