### ISSUE TITLE
Alexa Klein DC Neighborhood Restaurant Guide 

### ISSUE THREAD

**Issue by aklein916** [ga-dc/wdi8-project2-gallery#18]
Link to repo: https://github.com/aklein916/dc_guide
Link to deployed app:

Things you'd like specific feedback on:
At this point, nothing. I keep finding myself thinking really big and I need to remember to keep it simple to start and that I can build on that as I go.

**Comment by amaseda** [comment]
### Re: Planning

:+1: This all looks good! Just a couple notes below.

#### User Stories

Encourage you to write some user stories that outline specific application behavior (i.e., When a user clicks on this button, this happens).

#### Wireframes

Your wireframes are heavy on the data you'll be displaying. Use them to focus on visual layout. Might be helpful to create wireframes for your RESTful views (e.g., index, show, new, edit).
