### ISSUE TITLE
Casey_Solution

### ISSUE THREAD

**Issue by caseyagil** [ga-dc/wdi8-project2-gallery#24]
https://github.com/caseyagil/Project2

I think I might change it though, over the weekend I did not feel as confident about my project!

**Comment by beckybeauchamp1** [comment]
Hi Casey,

I would like to talk about your project when you have a chance. I did not see a `Planning Directory` and wanted to check if you were still going to move forward with your initial idea?

Please slack me tonight or tomorrow morning and we can discuss!
