### ISSUE TITLE
charleshwang_project 2

### ISSUE THREAD

**Issue by ghost** [ga-dc/wdi8-project2-gallery#26]
https://github.com/charlesthwang/climbr

This web app will allow climbers to keep track of routes they have completed at their local climbing centers.

**Comment by beckybeauchamp1** [comment]
Hi Charles,

Good job on the creating your planning directory! I think your wireframes look good, but it's condensed into the ERD.jpeg. I would make sure to try to abstract the wireframes out into it's own separate wireframes.jpeg. Also, I think in your `routes` table, specifically in your `set_date column`, you want the type to be `date` versus `string`  Please let me know if you have any further questions :+1:
