### ISSUE TITLE
Cam Latimer Project 2

### ISSUE THREAD

**Issue by CamLatimer** [ga-dc/wdi8-project2-gallery#28]
https://github.com/CamLatimer/project-2/tree/branch0

**Comment by beckybeauchamp1** [comment]
Hi Cam,

Hope your project is coming along well! I saw your user stories and wireframes- I would recommend adding them into a planning directory along with including your ERD. Also, I had a difficult time reading your wireframes, is there a way to expand the images?

Your user stories look great! Just remember throughout this week to focus on achieving your MVP first, then move on to silver and gold :+1:
