### ISSUE TITLE
Brittany Branson Monday Deliverable

### ISSUE THREAD

**Issue by Dibbledl01** [ga-dc/wdi8-project2-gallery#29]
https://github.com/Dibbledl01/project2_calledtobecreative

**Comment by beckybeauchamp1** [comment]
Hi Brittany,

Good evening! I took a look at your user stories, I would recommend putting them into a `Planning Directory` along with your `wireframes` and `ERD`. Also, what columns and tables are you planning to store in your DB? 

Just remember to focus on achieving your MVP first, with CRUD functionality then moving on to silver and gold.
