### ISSUE TITLE
Lyndsey's Issue

### ISSUE THREAD

**Issue by LNewsome** [ga-dc/wdi8-project2-gallery#30]
https://github.com/LNewsome/Punchlifeinthefaceproject

**Comment by mattscilipoti** [comment]
I recommend you delete readme.rdoc and create a readme.md, using MarkDown formatting options (https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/).  It should contain an overview of your app and information about planning.

**Comment by mattscilipoti** [comment]
User Stories look good.
Please clarify (in the stories), what you mean by "select the corresponding button".

I don't have access to the wireframes doc.  Do you have a way to make that link publicly available?
