### ISSUE TITLE
Live Unapologetically

### ISSUE THREAD

**Issue by kairajohnson** [ga-dc/wdi8-project2-gallery#34]
My app will connect different peoples experiences through life lessons. attached is the art direction I am going for (wireframe, title "untiled-4") and erb. The wireframe has dummy text.

https://github.com/kairajohnson/live-unapologetically

**Comment by joe-gz** [comment]
This looks like a god start Kaira! looking forward to seeing the finished product. just make sure to focus on the core functionality first, like we talked about last week :)

**Comment by kairajohnson** [comment]
I'm exited. I'm learning how to make rails  work with columns, the
comments, forms to create, and the basic functions to make a blog. I'm
hoping to get to the user side tomorrow.

**Comment by kairajohnson** [comment]
Haha, that should be excited, not exited 😭😭😭
