### ISSUE TITLE
maxkaye project2

### ISSUE THREAD

**Issue by MaxKaye** [ga-dc/wdi8-project2-gallery#35]
Link to repo: https://github.com/MaxKaye/contacts_project

Things you'd like specific feedback on:

**Comment by mattscilipoti** [comment]
:+1: Looks good.

Please either update readme.rdoc, or replace it with readme.md. https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/

**Comment by mattscilipoti** [comment]
The readme should have:
-  an overview of your project
- indicate where your planning docs are
- eventually, discuss your project
