### ISSUE TITLE
charleshwang_project2

### ISSUE THREAD

**Issue by ghost** [ga-dc/wdi8-project2-gallery#38]
Link to repo: https://github.com/charlesthwang/climbr/tree/styled_branch
Link to deployed app: https://climbr-beta.herokuapp.com
Link to presentation: https://www.youtube.com/watch?v=Eq6SYfV00MM&feature=youtu.be

Things you'd like specific feedback on:

**Comment by beckybeauchamp1** [comment]
Hi Charles,

Great job on Project 2! Here is the link to my PR with inline comments: https://github.com/charlesthwang/climbr/pull/1/files

Additionally, here is a link to the evaluation/feedback: https://github.com/beckybeauchamp1/climbr/blob/styled_branch/evaluation.md

Please let me know if you have any further questions :+1:
