### ISSUE TITLE
Christine Movius d&dr

### ISSUE THREAD

**Issue by christine-sm** [ga-dc/wdi8-project2-gallery#40]
YouTube: https://youtu.be/4nSx4Asty7g

App: https://dndr.herokuapp.com/

GitHub: https://github.com/cmmovius/dndr

Notes: For next steps I would really like to add users. In an ideal world, when a user signs in they can only view the campaign(s) to which they belong and can only edit the character(s) they create. What I'm getting tripped up on is a) they should still be able to view the characters created by their friends in their campaign but ONLY the ones in their campaign and b) the fact that many users can belong to many campaigns, but they should only be able to create one character within each campaign that they are a part of. Can I accomplish this simply with conditional view statements or would it require more than that?

**Comment by beckybeauchamp1** [comment]
Hi Christine, 

Great job on Project 2! Here is a link to my PR with comments and changes: https://github.com/cmmovius/dndr/pull/1/files

Additionally, here is a link to the evaluation.md file: https://github.com/beckybeauchamp1/dndr/blob/master/evaluation.md

In terms of your implementation with users, devise would definitely help a lot! You would do this a couple of ways. It might be helpful to use devise and cancancan together: https://github.com/CanCanCommunity/cancancan.

This would definitely be a many to many relationship with users and campaigns. Here is a link to the lesson plan to help with cancancan if you wanted to see it's implementation: https://github.com/ga-wdi-lessons/cancancan.

Also, we can pair on this sometime next week or the following if you would like to as well. Happy to help or answer any further questions :+1:
