### ISSUE TITLE
Emotional Corgum

### ISSUE THREAD

**Issue by holytoastr** [ga-dc/wdi8-project2-gallery#41]
Link to repo: https://github.com/holytoastr/project2
Link to deployed app: https://emotional-corgum.herokuapp.com
Link to video: https://youtu.be/BfuGJ4fSfo8

Things you'd like specific feedback on: What's one thing I could learn about and add that you think would take this to the next level?

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/holytoastr/project2/pull/1)
