### ISSUE TITLE
Patrick's Project 2 Submission

### ISSUE THREAD

**Issue by pkmoran** [ga-dc/wdi8-project2-gallery#43]
Link to repo: [Hopstr](https://github.com/pkmoran/hopstr-project-2)
Link to deployed app: [Hopstr on Heroku](http://hopstr.herokuapp.com/)
Link to youtube demo: [App Demo](https://www.youtube.com/watch?v=gksIySHtfHk)

Things you'd like specific feedback on:
I would love to have feedback on anything that could have DRY'd up my code. Also, I'm still unfamiliar with how and when to use model methods. Is there anything that I had in my controllers that could have been moved to a model?

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/pkmoran/hopstr-project-2/pull/1)
