### ISSUE TITLE
Casey_Soluton

### ISSUE THREAD

**Issue by caseyagil** [ga-dc/wdi8-project2-gallery#44]
Link to repo: https://github.com/caseyagil/msgboard
Link to deployed app: https://caseysboard.herokuapp.com
Youtube Link:  https://youtu.be/gHe4AbFGWLc

**Comment by beckybeauchamp1** [comment]
Hi Casey,

Good job on Project 2! Here is a link to my PR and a link to your Project evaluation/feedback:
PR:https://github.com/caseyagil/msgboard/pull/1/files
Feedback:https://github.com/beckybeauchamp1/msgboard/blob/master/evaluation.md

Please let me know if you have any further questions :+1:
