### ISSUE TITLE
Jeffrey Eaton's LifeList app

### ISSUE THREAD

**Issue by jeffreyeaton76** [ga-dc/wdi8-project2-gallery#56]
An app for birdwatchers to track sightings. 

GitHub repo: https://github.com/jeffreyeaton76/lifelist
Deployed app on Heroku: https://jeffreyeaton76-lifelist.herokuapp.com/
Video presentation: https://youtu.be/mss9yz59a3U

**Comment by joe-gz** [comment]
Great job Jeff! I submitted a PR to your repo with comments and a feedback md file. Here's the link!
https://github.com/jeffreyeaton76/lifelist/pull/1
