### ISSUE TITLE
Bipin's project 2

### ISSUE THREAD

**Issue by ghost** [ga-dc/wdi8-project2-gallery#57]
Link to repo: https://github.com/Bneupane/cheerup
Link to deployed app: https://projectcheerup.herokuapp.com/members/new
Link to Youtube: https://youtu.be/ChDUJIoE0ow

Things you'd like specific feedback on: 
creating link between user and their message so that i can see what messages i have posted.

**Comment by amaseda** [comment]
@Bneupane Left some comments on this in my project notes, but you can make sure of that association you set up to implement this functionality. Your code would look something like this...

``` rb
@member = Member.find(some_id)
@member.messages.create!(message_params)
```
