### ISSUE TITLE
mohamed's project 2 GamR

### ISSUE THREAD

**Issue by mohamedrchalal** [ga-dc/wdi8-project2-gallery#58]
youtube: https://www.youtube.com/watch?v=1g2MqVoFxX0
Heroku: https://gamr-mohamed.herokuapp.com/
GitHub: https://github.com/mohamedrchalal/GamR/tree/deploying

Things you'd like specific feedback on:

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/mohamedrchalal/GamR/pull/1)
