### ISSUE TITLE
Sanjaya's Project - Ice and Fire Wiki

### ISSUE THREAD

**Issue by ssatyal** [ga-dc/wdi8-project2-gallery#62]
Link to repo: https://github.com/ssatyal/ice_and_fire
Link to deployed app: https://ice-and-fire.herokuapp.com/
Link to youtube: https://youtu.be/BP696Um8JD4

Things you'd like specific feedback on: 
I haven't implemented the emails for forgotten passwords. Is this a worthwhile endeavor or should I just leave it alone for now?

**Comment by RobertAKARobin** [comment]
I'd absolutely leave it alone for now, but mailers aren't hard -- take a look, if you want!
