### ISSUE TITLE
Caitlin Project 2

### ISSUE THREAD

**Issue by caitlindaitch** [ga-dc/wdi8-project2-gallery#64]
YouTube: https://www.youtube.com/watch?v=EXk30_ArCek
Heroku: https://bar-in-mind.herokuapp.com
GitHub: https://github.com/caitlindaitch/bar_in_mind

Things you'd like specific feedback on:
I'm happy with my app, but I would love to add on a feature where you can store your favorite bars on a user profile page. I would love suggestions on how best to approach this. Thanks!

**Comment by beckybeauchamp1** [comment]
Hi Caitlin,

Great job on Project 2! Here are links to my PR and Feedback:

PR: https://github.com/caitlindaitch/bar_in_mind/pull/1
Feedback: https://github.com/beckybeauchamp1/bar_in_mind/blob/master/evaluation.md

In terms of adding favoriting functionality, this would be a many to many relationship, so you would need to add a joined table and joined model. 

```
class Favorite < ActiveRecord::Base
 belongs_to :bar
 belongs_to :user
end
```

Please let me know if you have any further questions :+1:
