### ISSUE TITLE
RSVPeeeezy

### ISSUE THREAD

**Issue by CamLatimer** [ga-dc/wdi8-project2-gallery#67]
Link to repo: https://github.com/CamLatimer/rsvpeeeezy
Link to deployed app:https://rsvpeeeezy.herokuapp.com/

Link to screencast: https://youtu.be/JLw5dFmd_ww

Things you'd like specific feedback on:
I know my version control is messy, all over the place.  So, general, or even advanced, tips on version control are appreciated.  

Also, ways tips on how to dry up my code.  Scope / feature creep got to me.  I may have benefitted from just focusing much more on core functionality and lost time I could've spent on DRY'ing up code, learning how to user patials, putting logic in the correct place, etc.

**Comment by beckybeauchamp1** [comment]
Hi Cam,

Great job on Project 2! Here is a link to my PR with added comments and changes: https://github.com/CamLatimer/rsvpeeeezy/pull/1/files

Please let me know if you have any further questions :+1:
