### ISSUE TITLE
John Blakeman Project 2 Submission

### ISSUE THREAD

**Issue by jblakeman** [ga-dc/wdi8-project2-gallery#70]
Link to repo: [https://github.com/jblakeman/link-share](https://github.com/jblakeman/link-share)
Link to deployed app: [https://link-share-app.herokuapp.com](https://link-share-app.herokuapp.com)
Link to video: [https://www.youtube.com/watch?v=JnfgVaRkvAo](https://www.youtube.com/watch?v=JnfgVaRkvAo)

Things you'd like specific feedback on:

Nested route implementation, controller methods, and views implementation.

**Comment by joe-gz** [comment]
Nice job John! Please see the below link for feedback. Let me know if you have any questions!
https://github.com/jblakeman/link-share/pull/1
