### ISSUE TITLE
Keith Prifte's Project 2: Thrive

### ISSUE THREAD

**Issue by khenry10** [ga-dc/wdi8-project2-gallery#73]
Link to repo: https://github.com/khenry10/thrive
Link to deployed app: https://thrive-list.herokuapp.com/
Link to screencast: https://www.youtube.com/watch?v=9bxsOEutHcs&feature=youtu.be

Things you'd like specific feedback on:  Adding more of the logic into model methods.

**Comment by joe-gz** [comment]
Great job Keith! I've left feedback in the below PR. There is a md file with my overall feedback, as well as in line comments:
https://github.com/khenry10/thrive/pull/1
