### ISSUE TITLE
Brittany Branson Project 2: Called To Be Creative submission

### ISSUE THREAD

**Issue by Dibbledl01** [ga-dc/wdi8-project2-gallery#75]
Link to repo: https://github.com/Dibbledl01/project2_calledtobecreative
Link to deployed app: https://called-to-be-creative.herokuapp.com/

Link to Vimeo video: https://vimeo.com/160247277
Link to YouTube video: https://youtu.be/ngT94d48RZU

**Comment by beckybeauchamp1** [comment]
Hi Brittany,

Good job on Project 2!! 

Here is a link to my PR and Evaluation Template:
PR: https://github.com/Dibbledl01/project2_calledtobecreative/pull/1/files
Evaluation: https://github.com/beckybeauchamp1/project2_calledtobecreative/blob/master/evaluation.md

Please let me know if you have any further questions :+1:
