### ISSUE TITLE
Ryan's Factorio Map Share

### ISSUE THREAD

**Issue by rkrolick** [ga-dc/wdi8-project2-gallery#79]
Link to repo: https://github.com/rkrolick/wdi_project2
Link to deployed app: http://factorio-map-share.herokuapp.com/factorio_maps
YouTube Link: https://www.youtube.com/watch?v=6sEUINPmVQM

Things you'd like specific feedback on:  I'm wondering if there's a better method for extracting the file and having paperclip read it from the server.   Aside from that feedback on readability of my code would be appreciated.

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/rkrolick/wdi_project2/pull/1)
