### ISSUE TITLE
Live Unapologetically- Kaira Johnson

### ISSUE THREAD

**Issue by kairajohnson** [ga-dc/wdi8-project2-gallery#83]
Link to repo:https://github.com/kairajohnson/live-unapologetically
Link to deployed app: https://live-unapologetically.herokuapp.com/
Screencast: https://youtu.be/sjDOBx-FFVY

Things you'd like specific feedback on: My heroku app looks completely different than my local. the html, images, etc.

**Comment by joe-gz** [comment]
nice job Kaira! Let me know if you have any questions after taking a look at the following PR:
https://github.com/kairajohnson/live-unapologetically/pull/3
