### ISSUE TITLE
Craig Eisen: BestBet

### ISSUE THREAD

**Issue by Ceisen9** [ga-dc/wdi8-project2-gallery#9]
Here is a link to my repo for project 2, titled BestBet:

https://github.com/Ceisen9/bestbet

The purpose of this app is to provide a useful database to navigate archival data from the National Football League's games since 2000 and to compare betting information to actual results. The data can be filtered by different subsets of the NFL including conferences, divisions, teams, and games. The information being presented will include games played, win/loss records (aggregate, home, and away) as well as various betting statistics like over-unders and betting lines.

**Comment by jshawl** [comment]
:+1: Excellent!
